<!-- Description: R: uma ferramenta de código aberto para análise de -->
<!-- dados / Docentes UNIVALI  -->
<!-- -->
<!-- Maintainer: UNIVALI  -->
<!-- Author: Rodrigo Sant Ana -->
<!-- Created: Seg Jul 13 16:27:16 2015 (-0300) -->
<!-- Version: 0.0.1 -->
<!--
	Last-Updated: Seg Jul 13 18:45:22 2015 (-0300)
               By: Rodrigo Sant Ana
-->
<!-- -->
<!-- URL: github.com/rodrigosantana/Curso_R_Intro_UNIVALI_2015 -->
<!-- Doc URL: github.com/rodrigosantana/Curso_R_Intro_UNIVALI_2015 -->
<!--  -->
<!-- Database info:  -->
<!--  -->
<!-- Commentary:  -->
<!-- Code: -->

---
output:
   knitrBootstrap::bootstrap_document:
      title: "Curso R Intro - UNIVALI/2015"
      theme: Journal
      highlight: Sunburst
      theme.chooser: TRUE
      highlight.chooser: TRUE
---

```{r setup, include=FALSE}
opts_chunk$set(comment = NA,
               bootstrap.panel = TRUE)
```

```{r, eval=FALSE, include=FALSE}
library(knitr)
library(knitrBootstrap)
library(rmarkdown)
```

### Introdução 



```{r}
rnorm(10)
```

```{r}
plot(rnorm(10))
```


<!-- The MIT License (MIT) -->
<!-- -->
<!-- Copyright (c) Rodrigo Sant'Ana -->
<!--  -->
<!-- Permission is hereby granted, free of charge, to any person  -->
<!-- obtaining a copy of this software and associated documentation  -->
<!-- files (the 'Software'), to deal in the Software without  -->
<!-- restriction, including without limitation the rights to use,  -->
<!-- copy, modify, merge, publish, distribute, sublicense, and/or  -->
<!-- sell copies of the Software, and to permit persons to whom the  -->
<!-- Software is furnished to do so, subject to the following  -->
<!-- conditions:  -->
<!--  -->
<!-- The above copyright notice and this permission notice shall be  -->
<!-- included in all copies or substantial portions of the Software. -->
<!--  -->
<!-- THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,  -->
<!-- EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES  -->
<!-- OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND -->
<!-- NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS  -->
<!-- BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN  -->
<!-- ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN  -->
<!-- CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  -->
<!-- SOFTWARE. -->

